spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:house_finance;
    username: kakaopay
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 3000
